using System;

namespace Trustev.Domain.Entities
{
    /// <summary>
    /// This is the Trustev decision object and contains the results of a Trustev decision on a Case. For more info see http://www.trustev.com/developers-v2#get-a-trustev-decision.
    /// </summary>
    public class Decision
    {
        /// <summary>
        /// This is the Id generated by the Trustev Platform
        /// </summary>
        public Guid Id { get; internal set; }

        /// <summary>
        /// The Id of the Case that this Decision was base on.
        /// </summary>
        public string CaseId { get; set; }

        ///<summary>
        /// Configuration Version
        /// </summary>
        public int Version { get; set; }

        /// <summary>
        /// The SessionId or the Case that this Decision was based on
        /// </summary>
        public Guid SessionId { get; set; }

        /// <summary>
        /// The Date Time that this Decision was generate at
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// The Result of the Trustev Decision. See http://www.trustev.com/developers-v2#get-a-trustev-decision for more into on this. 
        /// </summary>
        public Enums.DecisionResult Result { get; set; }

        /// <summary>
        /// This is the score that Trustev assigned the Case. This can be ignored.
        /// </summary>
        public int Score { get; set; }

        /// <summary>
        /// A Trustev Confidence Score represents our confidence on a Trustev Decision based on the level of details supplied within a Trustev Case. The Trustev Confidence Score is out of 100. 100 being all information was supplied and validated and 0 indicating that no information was contained within the Trustev Case.
        /// </summary>
        public int Confidence { get; set; }

        /// <summary>
        /// The Trustev Comment that trustev has added to this decision.
        /// </summary>
        public string Comment { get; set; }
    }
}
