// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

	/// <summary>
	/// 
	/// </summary>
	public enum AddressType {
				/// <summary>
		/// 
		/// </summary>
		Standard = 0,

		/// <summary>
		/// 
		/// </summary>
		Billing = 1,

		/// <summary>
		/// 
		/// </summary>
		Delivery = 2,

	}
}