
// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

		
	/// <summary>
	/// 
	/// </summary>
	public class AuthenticationRequest {

		#region Public properties

				
		/// <summary>
		/// This is your Site UserName, available from your API Keys accessed through the Trustev Dashboard
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string UserName;
		
		/// <summary>
		/// This is the current Timestamp in the format yyyy-MM-ddTHH:mm:ss.fffZ		/// See our FAQ section for more information.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.DateTime? Timestamp;
		
		/// <summary>
		/// This is a hashed value involving your Timestamp, Site Password, and Shared Secret.		/// Please see Step 5 of our Integration Documentation for information on how to form this.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string PasswordHash;
		
		/// <summary>
		/// This is a hashed value involving your Timestamp, Site UserName, and Shared Secret.		/// Please see Step 5 of our Integration Documentation for information on how to form this.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string UserNameHash;

		
		#endregion
		
		#region Constructor

		/// <summary>
		/// 
		/// </summary>
		/// <param name="jsonObject">JSON string defines object</param>
		public AuthenticationRequest(string jsonObject = null) {
		if(jsonObject!=null) {
				var desObj = JsonConvert.DeserializeObject<AuthenticationRequest>(jsonObject);
				this.UserName = desObj.UserName;
				this.Timestamp = desObj.Timestamp;
				this.PasswordHash = desObj.PasswordHash;
				this.UserNameHash = desObj.UserNameHash;
			}
		}

		#endregion
	}
}

