// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

	/// <summary>
	/// 
	/// </summary>
	public enum CaseSummarySortOptions {
				/// <summary>
		/// 
		/// </summary>
		DateAsc = 0,

		/// <summary>
		/// 
		/// </summary>
		DateDesc = 1,

		/// <summary>
		/// 
		/// </summary>
		Status = 2,

	}
}