
// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

		
	/// <summary>
	/// 
	/// </summary>
	public class CaseStatus {

		#region Public properties

				
		/// <summary>
		/// This is the Status Id. This Id is returned in the response header of the Add a Case method, when Status Information has been added.		/// This Id is required should you wish to retrieve the Status details after a Trustev Case has been added.		/// Please note: this Id is always returned from the Trustev API as a reference Id to the specific object.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.Guid? Id;
		
		/// <summary>
		/// The Status Type of the Trustev Case
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public CaseStatusType Status;
		
		/// <summary>
		/// Comment on the Status
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string Comment;
		
		/// <summary>
		/// Current Timestamp. Accepted format: yyyy-MM-ddTHH:mm:ss.fffZ		/// See our FAQ section for more information.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.DateTime? Timestamp;

		
		#endregion
		
		#region Constructor

		/// <summary>
		/// 
		/// </summary>
		/// <param name="jsonObject">JSON string defines object</param>
		public CaseStatus(string jsonObject = null) {
		if(jsonObject!=null) {
				var desObj = JsonConvert.DeserializeObject<CaseStatus>(jsonObject);
				this.Id = desObj.Id;
				this.Status = desObj.Status;
				this.Comment = desObj.Comment;
				this.Timestamp = desObj.Timestamp;
			}
		}

		#endregion
	}
}

