// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

	/// <summary>
	/// 
	/// </summary>
	public enum CaseStatusType {
				/// <summary>
		/// 
		/// </summary>
		Completed = 0,

		/// <summary>
		/// 
		/// </summary>
		RejectedFraud = 1,

		/// <summary>
		/// 
		/// </summary>
		RejectedAuthFailure = 2,

		/// <summary>
		/// 
		/// </summary>
		RejectedSuspicious = 3,

		/// <summary>
		/// 
		/// </summary>
		Cancelled = 4,

		/// <summary>
		/// 
		/// </summary>
		ChargebackFraud = 5,

		/// <summary>
		/// 
		/// </summary>
		ChargebackOther = 6,

		/// <summary>
		/// 
		/// </summary>
		Refunded = 7,

		/// <summary>
		/// 
		/// </summary>
		Placed = 8,

		/// <summary>
		/// 
		/// </summary>
		OnHoldReview = 9,

	}
}