
// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

		
	/// <summary>
	/// 
	/// </summary>
	public class Customer {

		#region Public properties

				
		/// <summary>
		/// This is the Customer Id. This Id is returned when Customer Information has been added.		/// This Id is required should you wish to update the Customer details after a Trustev Case has been added.		/// Please note: this Id is always returned from the Trustev API as a reference Id to the specific object.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.Guid? Id;
		
		/// <summary>
		/// The First Name of the Customer.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string FirstName;
		
		/// <summary>
		/// The Last Name of the Customer.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string LastName;
		
		/// <summary>
		/// A collection of Emails.		/// Please see Emails object for further parameter information.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public Email[] Emails;
		
		/// <summary>
		/// The Phone Number for the Customer.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string PhoneNumber;
		
		/// <summary>
		/// The Date of Birth of the Customer. Accepted format: yyyy-MM-ddTHH:mm:ss.fffZ		/// See our Timestamp FAQ section for more information.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.DateTime? DateOfBirth;
		
		/// <summary>
		/// Addresses Object â€“ Contains standard/delivery/billing information.		/// Please see Address Object for further parameter information.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public Address[] Addresses;
		
		/// <summary>
		/// Social Account Object â€“ Contains Short Term and Long Term Access Tokens, along with Social Account Ids and Types.		/// See Trustev Integration Documentation, http://developers.trustev.com/v2 for more information.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public SocialAccount[] SocialAccounts;
		
		/// <summary>
		/// The Account number of the Customer.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string AccountNumber;

		
		#endregion
		
		#region Constructor

		/// <summary>
		/// 
		/// </summary>
		/// <param name="jsonObject">JSON string defines object</param>
		public Customer(string jsonObject = null) {
		if(jsonObject!=null) {
				var desObj = JsonConvert.DeserializeObject<Customer>(jsonObject);
				this.Id = desObj.Id;
				this.FirstName = desObj.FirstName;
				this.LastName = desObj.LastName;
				this.Emails = desObj.Emails;
				this.PhoneNumber = desObj.PhoneNumber;
				this.DateOfBirth = desObj.DateOfBirth;
				this.Addresses = desObj.Addresses;
				this.SocialAccounts = desObj.SocialAccounts;
				this.AccountNumber = desObj.AccountNumber;
			}
		}

		#endregion
	}
}

