
// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

		
	/// <summary>
	/// 
	/// </summary>
	public class Email {

		#region Public properties

				
		/// <summary>
		/// This is the Email Id. This Id is returned when an Email Address has been added.		/// This Id is required should you wish to update the Email details after a Trustev Case has been added.		/// Please note: this Id is always returned from the Trustev API as a reference Id to the specific object.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.Guid? Id;
		
		/// <summary>
		/// Email Address of the customer
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string EmailAddress;
		
		/// <summary>
		/// Is this is the default email for the customer?
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsDefault;

		
		#endregion
		
		#region Constructor

		/// <summary>
		/// 
		/// </summary>
		/// <param name="jsonObject">JSON string defines object</param>
		public Email(string jsonObject = null) {
		if(jsonObject!=null) {
				var desObj = JsonConvert.DeserializeObject<Email>(jsonObject);
				this.Id = desObj.Id;
				this.EmailAddress = desObj.EmailAddress;
				this.IsDefault = desObj.IsDefault;
			}
		}

		#endregion
	}
}

