
// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

		
	/// <summary>
	/// 
	/// </summary>
	public class HttpResponseMessage {

		#region Public properties

				
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public Version Version;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public HttpContent Content;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public HttpStatusCode StatusCode;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string ReasonPhrase;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public Object[] Headers;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public HttpRequestMessage RequestMessage;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsSuccessStatusCode;

		
		#endregion
		
		#region Constructor

		/// <summary>
		/// 
		/// </summary>
		/// <param name="jsonObject">JSON string defines object</param>
		public HttpResponseMessage(string jsonObject = null) {
		if(jsonObject!=null) {
				var desObj = JsonConvert.DeserializeObject<HttpResponseMessage>(jsonObject);
				this.Version = desObj.Version;
				this.Content = desObj.Content;
				this.StatusCode = desObj.StatusCode;
				this.ReasonPhrase = desObj.ReasonPhrase;
				this.Headers = desObj.Headers;
				this.RequestMessage = desObj.RequestMessage;
				this.IsSuccessStatusCode = desObj.IsSuccessStatusCode;
			}
		}

		#endregion
	}
}

