// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

	/// <summary>
	/// 
	/// </summary>
	public enum PaymentType {
				/// <summary>
		/// 
		/// </summary>
		None = 0,

		/// <summary>
		/// 
		/// </summary>
		CreditCard = 1,

		/// <summary>
		/// 
		/// </summary>
		DebitCard = 2,

		/// <summary>
		/// 
		/// </summary>
		DirectDebit = 3,

		/// <summary>
		/// 
		/// </summary>
		PayPal = 4,

		/// <summary>
		/// 
		/// </summary>
		Bitcoin = 5,

	}
}