// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

	/// <summary>
	/// 
	/// </summary>
	public enum SocialNetworkType {
				/// <summary>
		/// 
		/// </summary>
		Facebook = 0,

		/// <summary>
		/// 
		/// </summary>
		Twitter = 1,

		/// <summary>
		/// 
		/// </summary>
		LinkedIn = 2,

		/// <summary>
		/// 
		/// </summary>
		Trustev = 3,

		/// <summary>
		/// 
		/// </summary>
		TrustevSession = 4,

	}
}