
// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

		
	/// <summary>
	/// 
	/// </summary>
	public class SocialAccount {

		#region Public properties

				
		/// <summary>
		/// This is the Social Account Id. This Id is returned when a Social Account object has been added to the Trustev API.		/// This Id is required should you wish to update the Social Account details after a Trustev Case has been added.		/// Please note: this Id is always returned from the Trustev API as a reference Id to the specific object.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.Guid? Id;
		
		/// <summary>
		/// This is the Social Network Id, i.e. Your Facebook Account Id
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public int? SocialId;
		
		/// <summary>
		/// This is your Trustev Social Network Type
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public SocialNetworkType Type;
		
		/// <summary>
		/// This is the Short Term Access Token which is available from the Social Access Token you received from the relevant Social Network&#39;s API
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string ShortTermAccessToken;
		
		/// <summary>
		/// This is the Long Term Access Token which is available from the Social Access Token you received from the relevant Social Network&#39;s API
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string LongTermAccessToken;
		
		/// <summary>
		/// This is the Short Term Token Expiry datetime which is available from the Social Access Token you received from the relevant Social Network&#39;s API
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.DateTime? ShortTermAccessTokenExpiry;
		
		/// <summary>
		/// This is the Long Term Token Expiry datetime which is available from the Social Access Token you received from the relevant Social Network&#39;s API
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.DateTime? LongTermAccessTokenExpiry;
		
		/// <summary>
		/// This is the Secret which is attached to the Social Network&#39;s Developer&#39;s Account. This would have previously been needed to access the relevant Social Network&#39;s API
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string Secret;
		
		/// <summary>
		/// Current Timestamp. Accepted format: yyyy-MM-ddTHH:mm:ss.fffZ		/// See our FAQ section for more information.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.DateTime? Timestamp;

		
		#endregion
		
		#region Constructor

		/// <summary>
		/// 
		/// </summary>
		/// <param name="jsonObject">JSON string defines object</param>
		public SocialAccount(string jsonObject = null) {
		if(jsonObject!=null) {
				var desObj = JsonConvert.DeserializeObject<SocialAccount>(jsonObject);
				this.Id = desObj.Id;
				this.SocialId = desObj.SocialId;
				this.Type = desObj.Type;
				this.ShortTermAccessToken = desObj.ShortTermAccessToken;
				this.LongTermAccessToken = desObj.LongTermAccessToken;
				this.ShortTermAccessTokenExpiry = desObj.ShortTermAccessTokenExpiry;
				this.LongTermAccessTokenExpiry = desObj.LongTermAccessTokenExpiry;
				this.Secret = desObj.Secret;
				this.Timestamp = desObj.Timestamp;
			}
		}

		#endregion
	}
}

