
// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

		
	/// <summary>
	/// 
	/// </summary>
	public class TransactionItem {

		#region Public properties

				
		/// <summary>
		/// This is the Item Id. This Id is returned when Item Information has been added to the Transaction object.		/// This Id is required should you wish to update the Item details after a Trustev Case has been added.		/// Please note: this Id is always returned from the Trustev API as a reference Id to the specific object.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public System.Guid? Id;
		
		/// <summary>
		/// The Name of the Item being purchased.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string Name;
		
		/// <summary>
		/// The Quantity of the Item being purchased.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public int? Quantity;
		
		/// <summary>
		/// The Value of the Item being purchased.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public decimal? ItemValue;

		
		#endregion
		
		#region Constructor

		/// <summary>
		/// 
		/// </summary>
		/// <param name="jsonObject">JSON string defines object</param>
		public TransactionItem(string jsonObject = null) {
		if(jsonObject!=null) {
				var desObj = JsonConvert.DeserializeObject<TransactionItem>(jsonObject);
				this.Id = desObj.Id;
				this.Name = desObj.Name;
				this.Quantity = desObj.Quantity;
				this.ItemValue = desObj.ItemValue;
			}
		}

		#endregion
	}
}

