
// Generated by ApiCrawler

using System;
using Trustev.Api.Client.Entities;
using Newtonsoft.Json;

namespace Trustev.Api.Client.Entities {

		
	/// <summary>
	/// 
	/// </summary>
	public class Version {

		#region Public properties

				
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public int? Major;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public int? Minor;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public int? Build;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public int? Revision;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public int? MajorRevision;
		
		/// <summary>

		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public int? MinorRevision;

		
		#endregion
		
		#region Constructor

		/// <summary>
		/// 
		/// </summary>
		/// <param name="jsonObject">JSON string defines object</param>
		public Version(string jsonObject = null) {
		if(jsonObject!=null) {
				var desObj = JsonConvert.DeserializeObject<Version>(jsonObject);
				this.Major = desObj.Major;
				this.Minor = desObj.Minor;
				this.Build = desObj.Build;
				this.Revision = desObj.Revision;
				this.MajorRevision = desObj.MajorRevision;
				this.MinorRevision = desObj.MinorRevision;
			}
		}

		#endregion
	}
}

